[tool.briefcase]
project_name = "tempratureconverter"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/tempratureconverter"
license = "BSD license"
author = 'nidhi'
author_email = "nidhifab77@gmail.com"

[tool.briefcase.app.tempratureconverter]
formal_name = "tempratureconverter"
description = "tempratureconverter"
icon = "src/tempratureconverter/resources/tempratureconverter"
sources = ['src/tempratureconverter']
requires = []


[tool.briefcase.app.tempratureconverter.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.tempratureconverter.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.tempratureconverter.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.tempratureconverter.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.tempratureconverter.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
